/**
 * 零凭证、零网络的正式调试 provider。
 *
 * 普通输入会得到可预测的流式 echo；以下指令会生成真实工具调用，便于在本地
 * 调 TUI 的授权、并行、todo 和 transcript，而不用消耗 API 额度：
 *   !todo · !write · !bash · !parallel
 */

import type {
  ChatMessage,
  Provider,
  StreamEvent,
  StreamRequest,
  ToolCallPart,
  ToolResultPart,
  Usage,
} from "../types.js";

export interface DebugProviderOptions {
  /** 文本分片之间的延迟；默认 12ms，测试可设 0。 */
  delayMs?: number;
  /** 每个文本分片的字符数。 */
  chunkSize?: number;
}

export class DebugProvider implements Provider {
  readonly name = "debug";
  private readonly delayMs: number;
  private readonly chunkSize: number;

  constructor(options: DebugProviderOptions = {}) {
    this.delayMs = finiteNonNegative(options.delayMs, 12);
    this.chunkSize = Math.max(1, Math.floor(finiteNonNegative(options.chunkSize, 12)));
  }

  async *stream(req: StreamRequest): AsyncIterable<StreamEvent> {
    throwIfAborted(req.signal);
    const results = latestToolResults(req.messages);
    if (results.length > 0) {
      const summary = results
        .map(
          (result) => `${result.toolName}: ${result.isError ? "失败" : "完成"} — ${result.content}`,
        )
        .join("\n");
      yield* this.textResponse(`Debug 工具回合结束：\n${summary}`, req);
      return;
    }

    const input = latestUserText(req.messages);
    const calls = directiveCalls(input);
    if (calls) {
      yield* this.toolResponse(calls, req);
      return;
    }

    const text = input
      ? `Debug provider (${req.model}) 收到：${input}`
      : `Debug provider (${req.model}) 已就绪。输入 !todo、!write、!bash 或 !parallel 可调试工具流程。`;
    yield* this.textResponse(text, req);
  }

  private async *textResponse(text: string, req: StreamRequest): AsyncIterable<StreamEvent> {
    for (let i = 0; i < text.length; i += this.chunkSize) {
      throwIfAborted(req.signal);
      const chunk = text.slice(i, i + this.chunkSize);
      yield { type: "text_delta", text: chunk };
      if (this.delayMs > 0) await wait(this.delayMs, req.signal);
    }
    const message: ChatMessage = { role: "assistant", content: [{ type: "text", text }] };
    yield { type: "done", stopReason: "end_turn", message, usage: debugUsage(req, text.length) };
  }

  private async *toolResponse(
    calls: ToolCallPart[],
    req: StreamRequest,
  ): AsyncIterable<StreamEvent> {
    for (const call of calls) {
      throwIfAborted(req.signal);
      yield { type: "tool_call_start", id: call.id, name: call.name };
      const json = JSON.stringify(call.args);
      const middle = Math.max(1, Math.ceil(json.length / 2));
      for (const argsText of [json.slice(0, middle), json.slice(middle)]) {
        if (!argsText) continue;
        yield { type: "tool_call_delta", id: call.id, argsText };
        if (this.delayMs > 0) await wait(this.delayMs, req.signal);
      }
      yield { type: "tool_call_end", part: call };
    }
    const message: ChatMessage = { role: "assistant", content: calls };
    yield {
      type: "done",
      stopReason: "tool_use",
      message,
      usage: debugUsage(req, JSON.stringify(calls).length),
    };
  }
}

function directiveCalls(input: string): ToolCallPart[] | null {
  const directive = input.trim().split(/\s+/, 1)[0]?.toLowerCase();
  switch (directive) {
    case "!todo":
      return [
        call("debug_todo_1", "todo_write", {
          todos: [
            {
              content: "验证 DebugProvider 工具调用",
              status: "in_progress",
              activeForm: "正在验证调试 provider",
            },
            { content: "检查 TUI 流式与进度显示", status: "pending" },
          ],
        }),
      ];
    case "!write":
      return [
        call("debug_write_1", "write", {
          path: ".anicode-debug.txt",
          content: "Generated by anicode DebugProvider.\n",
        }),
      ];
    case "!bash":
      return [call("debug_bash_1", "bash", { command: "printf 'anicode debug provider\\n'" })];
    case "!parallel":
      return [
        call("debug_parallel_1", "glob", { pattern: "packages/*/package.json" }),
        call("debug_parallel_2", "read", { path: "README.md", limit: 40 }),
      ];
    default:
      return null;
  }
}

function call(id: string, name: string, args: Record<string, unknown>): ToolCallPart {
  return { type: "tool_call", id, name, args };
}

function latestUserText(messages: ChatMessage[]): string {
  for (let i = messages.length - 1; i >= 0; i--) {
    const message = messages[i]!;
    if (message.role !== "user") continue;
    const text = message.content
      .filter((part) => part.type === "text")
      .map((part) => part.text)
      .join("\n")
      .trim();
    if (text) return text;
  }
  return "";
}

function latestToolResults(messages: ChatMessage[]): ToolResultPart[] {
  const last = messages[messages.length - 1];
  if (!last || last.role !== "user") return [];
  return last.content.filter((part): part is ToolResultPart => part.type === "tool_result");
}

function debugUsage(req: StreamRequest, outputChars: number): Usage {
  let inputChars = req.system?.length ?? 0;
  for (const message of req.messages) {
    for (const part of message.content) {
      if (part.type === "text" || part.type === "thinking") inputChars += part.text.length;
      else if (part.type === "tool_call")
        inputChars += part.name.length + JSON.stringify(part.args).length;
      else if (part.type === "tool_result") inputChars += part.content.length;
      else inputChars += 1000;
    }
  }
  return {
    inputTokens: Math.ceil(inputChars / 4),
    outputTokens: Math.ceil(outputChars / 4),
    cacheReadTokens: 0,
    cacheWriteTokens: 0,
  };
}

function finiteNonNegative(value: number | undefined, fallback: number): number {
  return value !== undefined && Number.isFinite(value) && value >= 0 ? value : fallback;
}

function throwIfAborted(signal: AbortSignal | undefined): void {
  if (!signal?.aborted) return;
  const error = new Error("DebugProvider request aborted");
  error.name = "AbortError";
  throw error;
}

async function wait(ms: number, signal: AbortSignal | undefined): Promise<void> {
  if (!signal) {
    await new Promise((resolve) => setTimeout(resolve, ms));
    return;
  }
  await new Promise<void>((resolve, reject) => {
    const timer = setTimeout(done, ms);
    const onAbort = () => {
      cleanup();
      const error = new Error("DebugProvider request aborted");
      error.name = "AbortError";
      reject(error);
    };
    function cleanup() {
      clearTimeout(timer);
      signal!.removeEventListener("abort", onAbort);
    }
    function done() {
      cleanup();
      resolve();
    }
    signal.addEventListener("abort", onAbort, { once: true });
    if (signal.aborted) onAbort();
  });
}
