/** GENERATED by npm run codegen — do not edit manually. */
export const OPENAPI_CONTRACT_SHA256 =
  "a6baefa5e35e0d8ddba5bb962ec40008f787c9d06d2b163f593caeae204b9cb2" as const;
export const GENERATED_ROUTES = {
  getHealthz: {
    method: "GET",
    template: "/healthz",
  },
  getGlobalHealth: {
    method: "GET",
    template: "/global/health",
  },
  getDoc: {
    method: "GET",
    template: "/doc",
  },
  getEvents: {
    method: "GET",
    template: "/events",
  },
  getSessions: {
    method: "GET",
    template: "/sessions",
  },
  postSessions: {
    method: "POST",
    template: "/sessions",
  },
  getSessionsId: {
    method: "GET",
    template: "/sessions/{id}",
  },
  deleteSessionsId: {
    method: "DELETE",
    template: "/sessions/{id}",
  },
  patchSessionsId: {
    method: "PATCH",
    template: "/sessions/{id}",
  },
  getSessionsIdEvents: {
    method: "GET",
    template: "/sessions/{id}/events",
  },
  getSessionsIdMessages: {
    method: "GET",
    template: "/sessions/{id}/messages",
  },
  getSessionsIdCheckpoints: {
    method: "GET",
    template: "/sessions/{id}/checkpoints",
  },
  getSessionsIdArtifacts: {
    method: "GET",
    template: "/sessions/{id}/artifacts",
  },
  postSessionsIdArtifacts: {
    method: "POST",
    template: "/sessions/{id}/artifacts",
  },
  getSessionsIdArtifactsArtifactId: {
    method: "GET",
    template: "/sessions/{id}/artifacts/{artifactId}",
  },
  deleteSessionsIdArtifactsArtifactId: {
    method: "DELETE",
    template: "/sessions/{id}/artifacts/{artifactId}",
  },
  postSessionsIdPatchsets: {
    method: "POST",
    template: "/sessions/{id}/patchsets",
  },
  getSessionsIdPatchsetsPatchsetId: {
    method: "GET",
    template: "/sessions/{id}/patchsets/{patchsetId}",
  },
  postSessionsIdPatchsetsPatchsetIdApprove: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/approve",
  },
  postSessionsIdPatchsetsPatchsetIdApply: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/apply",
  },
  postSessionsIdPatchsetsPatchsetIdRebase: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/rebase",
  },
  postSessionsIdPatchsetsPatchsetIdRollback: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/rollback",
  },
  getSessionsIdRuntimeEvents: {
    method: "GET",
    template: "/sessions/{id}/runtime-events",
  },
  getSessionsIdRuntimeState: {
    method: "GET",
    template: "/sessions/{id}/runtime-state",
  },
  postSessionsIdSend: {
    method: "POST",
    template: "/sessions/{id}/send",
  },
  postSessionsIdInterrupt: {
    method: "POST",
    template: "/sessions/{id}/interrupt",
  },
  postSessionsIdUndo: {
    method: "POST",
    template: "/sessions/{id}/undo",
  },
  postSessionsIdCompact: {
    method: "POST",
    template: "/sessions/{id}/compact",
  },
  postSessionsIdFork: {
    method: "POST",
    template: "/sessions/{id}/fork",
  },
  postSessionsIdPermission: {
    method: "POST",
    template: "/sessions/{id}/permission",
  },
  postSessionsIdPermissionMode: {
    method: "POST",
    template: "/sessions/{id}/permission-mode",
  },
  postSessionsIdPermissionProfile: {
    method: "POST",
    template: "/sessions/{id}/permission-profile",
  },
  getSessionsIdPermissionProfiles: {
    method: "GET",
    template: "/sessions/{id}/permission-profiles",
  },
} as const;
export type GeneratedOperationId = keyof typeof GENERATED_ROUTES;

export function generatedPath(
  operationId: GeneratedOperationId,
  params: Record<string, string | number> = {},
): string {
  const template = GENERATED_ROUTES[operationId].template as string;
  return template.replace(/\{([^}]+)\}/g, (_match, name: string) => {
    const value = params[name];
    if (value === undefined) throw new Error(`Missing path parameter ${name} for ${operationId}`);
    return encodeURIComponent(String(value));
  });
}
