/** GENERATED by npm run codegen — do not edit manually. */
export const OPENAPI_CONTRACT_SHA256 =
  "d3ea17964e9564111cd5df3f2d51b7d2020630a7fb1d0ddcae955a9d9debe289" as const;
export const GENERATED_OPERATIONS = {
  getHealthz: {
    method: "GET",
    template: "/healthz",
    tag: "global",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
    ],
  },
  getGlobalHealth: {
    method: "GET",
    template: "/global/health",
    tag: "global",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
      properties: {
        ok: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        protocol: {
          type: "integer",
        },
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
    ],
  },
  getDoc: {
    method: "GET",
    template: "/doc",
    tag: "global",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
    ],
  },
  getEvents: {
    method: "GET",
    template: "/events",
    tag: "global",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "text/event-stream",
    responseSchema: {
      $ref: "#/components/schemas/EventEnvelope",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
    ],
  },
  getSessions: {
    method: "GET",
    template: "/sessions",
    tag: "session",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SessionSummary",
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "limit",
        in: "query",
        description: "分页大小；省略时兼容返回全部会话",
        schema: {
          type: "integer",
          minimum: 1,
          maximum: 200,
        },
      },
      {
        name: "cursor",
        in: "query",
        description: "上一页 x-anicode-next-cursor 返回的不透明游标",
        schema: {
          type: "string",
          minLength: 1,
          maxLength: 256,
        },
      },
    ],
  },
  postSessions: {
    method: "POST",
    template: "/sessions",
    tag: "session",
    requestSchema: {
      type: "object",
      required: ["cwd", "model"],
      properties: {
        cwd: {
          type: "string",
          minLength: 1,
          maxLength: 32768,
        },
        model: {
          type: "string",
          minLength: 1,
          maxLength: 512,
        },
        title: {
          type: "string",
          minLength: 1,
          maxLength: 4096,
        },
      },
      additionalProperties: false,
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      $ref: "#/components/schemas/SessionSummary",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
    ],
  },
  getSessionsId: {
    method: "GET",
    template: "/sessions/{id}",
    tag: "session",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      $ref: "#/components/schemas/SessionSnapshot",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  deleteSessionsId: {
    method: "DELETE",
    template: "/sessions/{id}",
    tag: "session",
    requestSchema: null,
    responseStatus: 204,
    responseMediaType: null,
    responseSchema: null,
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  patchSessionsId: {
    method: "PATCH",
    template: "/sessions/{id}",
    tag: "session",
    requestSchema: {
      type: "object",
      required: ["title"],
      properties: {
        title: {
          type: "string",
          minLength: 1,
          maxLength: 4096,
        },
      },
      additionalProperties: false,
    },
    responseStatus: 204,
    responseMediaType: null,
    responseSchema: null,
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  getSessionsIdEvents: {
    method: "GET",
    template: "/sessions/{id}/events",
    tag: "session",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "text/event-stream",
    responseSchema: {
      $ref: "#/components/schemas/EventEnvelope",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  getSessionsIdMessages: {
    method: "GET",
    template: "/sessions/{id}/messages",
    tag: "message",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "array",
      items: {
        $ref: "#/components/schemas/MessageWithParts",
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  getSessionsIdCheckpoints: {
    method: "GET",
    template: "/sessions/{id}/checkpoints",
    tag: "session",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Checkpoint",
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  getSessionsIdArtifacts: {
    method: "GET",
    template: "/sessions/{id}/artifacts",
    tag: "artifact",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Artifact",
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdArtifacts: {
    method: "POST",
    template: "/sessions/{id}/artifacts",
    tag: "artifact",
    requestSchema: {
      type: "object",
      required: ["kind", "name"],
      oneOf: [
        {
          required: ["text"],
        },
        {
          required: ["dataBase64"],
        },
      ],
      properties: {
        kind: {
          type: "string",
          enum: [
            "plan",
            "patch",
            "diff",
            "verification",
            "log",
            "report",
            "screenshot",
            "file",
            "other",
          ],
        },
        name: {
          type: "string",
          minLength: 1,
        },
        mediaType: {
          type: "string",
        },
        text: {
          type: "string",
        },
        dataBase64: {
          type: "string",
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$",
        },
        metadata: {
          type: "object",
        },
      },
      additionalProperties: false,
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      $ref: "#/components/schemas/Artifact",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  getSessionsIdArtifactsArtifactId: {
    method: "GET",
    template: "/sessions/{id}/artifacts/{artifactId}",
    tag: "artifact",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
      properties: {
        artifact: {
          $ref: "#/components/schemas/Artifact",
        },
        dataBase64: {
          type: "string",
        },
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
      {
        name: "artifactId",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  getSessionsIdArtifactsArtifactIdContent: {
    method: "GET",
    template: "/sessions/{id}/artifacts/{artifactId}/content",
    tag: "artifact",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/octet-stream",
    responseSchema: {
      type: "string",
      format: "binary",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
      {
        name: "artifactId",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  deleteSessionsIdArtifactsArtifactId: {
    method: "DELETE",
    template: "/sessions/{id}/artifacts/{artifactId}",
    tag: "artifact",
    requestSchema: null,
    responseStatus: 204,
    responseMediaType: null,
    responseSchema: null,
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
      {
        name: "artifactId",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdPatchsets: {
    method: "POST",
    template: "/sessions/{id}/patchsets",
    tag: "patchset",
    requestSchema: {
      type: "object",
      required: ["changes"],
      properties: {
        changes: {
          type: "array",
          minItems: 1,
          items: {
            type: "object",
            required: ["path"],
            properties: {
              path: {
                type: "string",
              },
              text: {
                type: "string",
              },
              dataBase64: {
                type: "string",
              },
              delete: {
                type: "boolean",
              },
              renameFrom: {
                type: "string",
              },
            },
            additionalProperties: false,
          },
        },
        requiredApprovals: {
          type: "integer",
          minimum: 0,
        },
        requiredRoles: {
          type: "array",
          items: {
            type: "string",
          },
        },
      },
      additionalProperties: false,
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
      properties: {
        patchset: {
          $ref: "#/components/schemas/PatchSet",
        },
        preview: {
          type: "string",
        },
        artifact: {
          $ref: "#/components/schemas/Artifact",
        },
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  getSessionsIdPatchsetsPatchsetId: {
    method: "GET",
    template: "/sessions/{id}/patchsets/{patchsetId}",
    tag: "patchset",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
      properties: {
        patchset: {
          $ref: "#/components/schemas/PatchSet",
        },
        preview: {
          type: "string",
        },
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
      {
        name: "patchsetId",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdPatchsetsPatchsetIdApprove: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/approve",
    tag: "patchset",
    requestSchema: {
      type: "object",
      required: ["actor", "role", "decision"],
      properties: {
        actor: {
          type: "string",
        },
        role: {
          type: "string",
        },
        decision: {
          type: "string",
          enum: ["approve", "reject"],
        },
        comment: {
          type: "string",
        },
      },
      additionalProperties: false,
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      $ref: "#/components/schemas/PatchSet",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
      {
        name: "patchsetId",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdPatchsetsPatchsetIdApply: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/apply",
    tag: "patchset",
    requestSchema: {
      type: "object",
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      $ref: "#/components/schemas/PatchSet",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
      {
        name: "patchsetId",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdPatchsetsPatchsetIdRebase: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/rebase",
    tag: "patchset",
    requestSchema: {
      type: "object",
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
      properties: {
        patchset: {
          $ref: "#/components/schemas/PatchSet",
        },
        conflictedPaths: {
          type: "array",
          items: {
            type: "string",
          },
        },
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
      {
        name: "patchsetId",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdPatchsetsPatchsetIdRollback: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/rollback",
    tag: "patchset",
    requestSchema: {
      type: "object",
      properties: {
        force: {
          type: "boolean",
        },
      },
      additionalProperties: false,
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      $ref: "#/components/schemas/PatchSet",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
      {
        name: "patchsetId",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  getSessionsIdRuntimeEvents: {
    method: "GET",
    template: "/sessions/{id}/runtime-events",
    tag: "runtime",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "array",
      items: {
        $ref: "#/components/schemas/RuntimeEvent",
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
      {
        name: "afterSequence",
        in: "query",
        schema: {
          type: "integer",
          minimum: 0,
        },
      },
    ],
  },
  getSessionsIdRuntimeState: {
    method: "GET",
    template: "/sessions/{id}/runtime-state",
    tag: "runtime",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdSend: {
    method: "POST",
    template: "/sessions/{id}/send",
    tag: "message",
    requestSchema: {
      type: "object",
      required: ["text"],
      properties: {
        text: {
          type: "string",
          minLength: 1,
          maxLength: 2097152,
        },
        model: {
          type: "string",
          minLength: 1,
          maxLength: 512,
        },
        idempotencyKey: {
          type: "string",
          minLength: 1,
          maxLength: 256,
        },
      },
      additionalProperties: false,
    },
    responseStatus: 204,
    responseMediaType: null,
    responseSchema: null,
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
      {
        name: "Idempotency-Key",
        in: "header",
        description: "重试安全的 command 幂等键；优先于同名 JSON 字段",
        schema: {
          type: "string",
          minLength: 1,
          maxLength: 256,
        },
      },
    ],
  },
  postSessionsIdInterrupt: {
    method: "POST",
    template: "/sessions/{id}/interrupt",
    tag: "session",
    requestSchema: {
      type: "object",
    },
    responseStatus: 204,
    responseMediaType: null,
    responseSchema: null,
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdUndo: {
    method: "POST",
    template: "/sessions/{id}/undo",
    tag: "session",
    requestSchema: {
      type: "object",
      properties: {
        checkpointId: {
          type: "string",
          minLength: 1,
          maxLength: 256,
        },
        mode: {
          type: "string",
          enum: ["files", "conversation", "both"],
        },
      },
      additionalProperties: false,
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
      properties: {
        restored: {
          type: "integer",
        },
        deleted: {
          type: "integer",
        },
        removedMessages: {
          type: "integer",
        },
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdCompact: {
    method: "POST",
    template: "/sessions/{id}/compact",
    tag: "session",
    requestSchema: {
      type: "object",
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
      properties: {
        compacted: {
          type: "boolean",
        },
        beforeTokens: {
          type: "integer",
        },
        afterTokens: {
          type: "integer",
        },
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdFork: {
    method: "POST",
    template: "/sessions/{id}/fork",
    tag: "session",
    requestSchema: {
      type: "object",
      properties: {
        title: {
          type: "string",
          minLength: 1,
          maxLength: 4096,
        },
        upToMessage: {
          type: "integer",
          minimum: 0,
        },
        model: {
          type: "string",
          minLength: 1,
          maxLength: 512,
        },
      },
      additionalProperties: false,
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      $ref: "#/components/schemas/SessionSummary",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdPermission: {
    method: "POST",
    template: "/sessions/{id}/permission",
    tag: "permission",
    requestSchema: {
      type: "object",
      required: ["permId", "decision"],
      properties: {
        permId: {
          type: "string",
          minLength: 1,
          maxLength: 256,
        },
        decision: {
          type: "string",
          enum: ["allow", "allow_remember", "allow_always", "deny"],
        },
      },
      additionalProperties: false,
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
      properties: {
        answered: {
          type: "boolean",
        },
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdPermissionMode: {
    method: "POST",
    template: "/sessions/{id}/permission-mode",
    tag: "permission",
    requestSchema: {
      type: "object",
      required: ["mode"],
      properties: {
        mode: {
          type: "string",
          enum: ["default", "acceptEdits", "auto", "bypass", "plan"],
        },
      },
      additionalProperties: false,
    },
    responseStatus: 204,
    responseMediaType: null,
    responseSchema: null,
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  postSessionsIdPermissionProfile: {
    method: "POST",
    template: "/sessions/{id}/permission-profile",
    tag: "permission",
    requestSchema: {
      type: "object",
      required: ["name"],
      properties: {
        name: {
          type: "string",
          minLength: 1,
          maxLength: 128,
        },
      },
      additionalProperties: false,
    },
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
      properties: {
        mode: {
          type: "string",
        },
      },
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
  getSessionsIdPermissionProfiles: {
    method: "GET",
    template: "/sessions/{id}/permission-profiles",
    tag: "permission",
    requestSchema: null,
    responseStatus: 200,
    responseMediaType: "application/json",
    responseSchema: {
      type: "object",
    },
    parameters: [
      {
        $ref: "#/components/parameters/ApiVersion",
      },
      {
        $ref: "#/components/parameters/RequestId",
      },
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
  },
} as const;
export const GENERATED_ROUTES = {
  getHealthz: {
    method: "GET",
    template: "/healthz",
  },
  getGlobalHealth: {
    method: "GET",
    template: "/global/health",
  },
  getDoc: {
    method: "GET",
    template: "/doc",
  },
  getEvents: {
    method: "GET",
    template: "/events",
  },
  getSessions: {
    method: "GET",
    template: "/sessions",
  },
  postSessions: {
    method: "POST",
    template: "/sessions",
  },
  getSessionsId: {
    method: "GET",
    template: "/sessions/{id}",
  },
  deleteSessionsId: {
    method: "DELETE",
    template: "/sessions/{id}",
  },
  patchSessionsId: {
    method: "PATCH",
    template: "/sessions/{id}",
  },
  getSessionsIdEvents: {
    method: "GET",
    template: "/sessions/{id}/events",
  },
  getSessionsIdMessages: {
    method: "GET",
    template: "/sessions/{id}/messages",
  },
  getSessionsIdCheckpoints: {
    method: "GET",
    template: "/sessions/{id}/checkpoints",
  },
  getSessionsIdArtifacts: {
    method: "GET",
    template: "/sessions/{id}/artifacts",
  },
  postSessionsIdArtifacts: {
    method: "POST",
    template: "/sessions/{id}/artifacts",
  },
  getSessionsIdArtifactsArtifactId: {
    method: "GET",
    template: "/sessions/{id}/artifacts/{artifactId}",
  },
  getSessionsIdArtifactsArtifactIdContent: {
    method: "GET",
    template: "/sessions/{id}/artifacts/{artifactId}/content",
  },
  deleteSessionsIdArtifactsArtifactId: {
    method: "DELETE",
    template: "/sessions/{id}/artifacts/{artifactId}",
  },
  postSessionsIdPatchsets: {
    method: "POST",
    template: "/sessions/{id}/patchsets",
  },
  getSessionsIdPatchsetsPatchsetId: {
    method: "GET",
    template: "/sessions/{id}/patchsets/{patchsetId}",
  },
  postSessionsIdPatchsetsPatchsetIdApprove: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/approve",
  },
  postSessionsIdPatchsetsPatchsetIdApply: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/apply",
  },
  postSessionsIdPatchsetsPatchsetIdRebase: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/rebase",
  },
  postSessionsIdPatchsetsPatchsetIdRollback: {
    method: "POST",
    template: "/sessions/{id}/patchsets/{patchsetId}/rollback",
  },
  getSessionsIdRuntimeEvents: {
    method: "GET",
    template: "/sessions/{id}/runtime-events",
  },
  getSessionsIdRuntimeState: {
    method: "GET",
    template: "/sessions/{id}/runtime-state",
  },
  postSessionsIdSend: {
    method: "POST",
    template: "/sessions/{id}/send",
  },
  postSessionsIdInterrupt: {
    method: "POST",
    template: "/sessions/{id}/interrupt",
  },
  postSessionsIdUndo: {
    method: "POST",
    template: "/sessions/{id}/undo",
  },
  postSessionsIdCompact: {
    method: "POST",
    template: "/sessions/{id}/compact",
  },
  postSessionsIdFork: {
    method: "POST",
    template: "/sessions/{id}/fork",
  },
  postSessionsIdPermission: {
    method: "POST",
    template: "/sessions/{id}/permission",
  },
  postSessionsIdPermissionMode: {
    method: "POST",
    template: "/sessions/{id}/permission-mode",
  },
  postSessionsIdPermissionProfile: {
    method: "POST",
    template: "/sessions/{id}/permission-profile",
  },
  getSessionsIdPermissionProfiles: {
    method: "GET",
    template: "/sessions/{id}/permission-profiles",
  },
} as const;
export type GeneratedOperationId = keyof typeof GENERATED_OPERATIONS;

export function generatedPath(
  operationId: GeneratedOperationId,
  params: Record<string, string | number> = {},
): string {
  const template = GENERATED_ROUTES[operationId].template as string;
  return template.replace(/\{([^}]+)\}/g, (_match, name: string) => {
    const value = params[name];
    if (value === undefined) throw new Error(`Missing path parameter ${name} for ${operationId}`);
    return encodeURIComponent(String(value));
  });
}

type GeneratedJsonSchema = {
  type?: string;
  required?: readonly string[];
  properties?: Record<string, GeneratedJsonSchema>;
  items?: GeneratedJsonSchema;
  additionalProperties?: boolean;
  enum?: readonly unknown[];
  const?: unknown;
  oneOf?: readonly GeneratedJsonSchema[];
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
  minimum?: number;
  maximum?: number;
  pattern?: string;
};

function sameGeneratedValue(left: unknown, right: unknown): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

function generatedSchemaIssues(value: unknown, schema: GeneratedJsonSchema, at = "$"): string[] {
  const issues: string[] = [];
  if (schema.const !== undefined && !sameGeneratedValue(value, schema.const))
    issues.push(at + ": const");
  if (schema.enum && !schema.enum.some((item) => sameGeneratedValue(item, value)))
    issues.push(at + ": enum");
  if (schema.oneOf) {
    const matches = schema.oneOf.filter(
      (branch) => generatedSchemaIssues(value, branch, at).length === 0,
    ).length;
    if (matches !== 1) issues.push(at + ": oneOf");
  }
  const object = value !== null && typeof value === "object" && !Array.isArray(value);
  const validType =
    schema.type === undefined ||
    (schema.type === "object" && object) ||
    (schema.type === "array" && Array.isArray(value)) ||
    (schema.type === "string" && typeof value === "string") ||
    (schema.type === "boolean" && typeof value === "boolean") ||
    (schema.type === "number" && typeof value === "number" && Number.isFinite(value)) ||
    (schema.type === "integer" && typeof value === "number" && Number.isSafeInteger(value));
  if (!validType) return [...issues, at + ": type"];
  if (object) {
    const record = value as Record<string, unknown>;
    for (const key of schema.required ?? [])
      if (!(key in record)) issues.push(at + "." + key + ": required");
    for (const [key, child] of Object.entries(schema.properties ?? {})) {
      if (key in record) issues.push(...generatedSchemaIssues(record[key], child, at + "." + key));
    }
    if (schema.additionalProperties === false) {
      for (const key of Object.keys(record))
        if (!(key in (schema.properties ?? {})))
          issues.push(at + "." + key + ": additionalProperties");
    }
  }
  if (Array.isArray(value)) {
    if (schema.minItems !== undefined && value.length < schema.minItems)
      issues.push(at + ": minItems");
    if (schema.maxItems !== undefined && value.length > schema.maxItems)
      issues.push(at + ": maxItems");
    if (schema.items)
      value.forEach((item, index) =>
        issues.push(...generatedSchemaIssues(item, schema.items!, at + "[" + index + "]")),
      );
  }
  if (typeof value === "string") {
    if (schema.minLength !== undefined && value.length < schema.minLength)
      issues.push(at + ": minLength");
    if (schema.maxLength !== undefined && value.length > schema.maxLength)
      issues.push(at + ": maxLength");
    if (schema.pattern && !new RegExp(schema.pattern).test(value)) issues.push(at + ": pattern");
  }
  if (typeof value === "number") {
    if (schema.minimum !== undefined && value < schema.minimum) issues.push(at + ": minimum");
    if (schema.maximum !== undefined && value > schema.maximum) issues.push(at + ": maximum");
  }
  return issues.slice(0, 64);
}

export function generatedRequestIssues(
  operationId: GeneratedOperationId,
  value: unknown,
): string[] {
  const schema = GENERATED_OPERATIONS[operationId].requestSchema as GeneratedJsonSchema | null;
  return schema ? generatedSchemaIssues(value, schema) : [];
}
