import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import {
  ROUTES,
  generateOpenApi,
  operationIdFor,
  validateOpenApiDocument,
} from "../../core/src/daemon/api.js";

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const output = path.resolve(currentDir, "../src/generated.ts");
const document = generateOpenApi();
const errors = validateOpenApiDocument(document);
if (errors.length) throw new Error(`OpenAPI conformance failed:\n${errors.join("\n")}`);
const contractHash = createHash("sha256").update(JSON.stringify(document)).digest("hex");
const routes = Object.fromEntries(
  ROUTES.map((route) => [
    operationIdFor(route),
    { method: route.method.toUpperCase(), template: route.path },
  ]),
);
const prettierConfig = (await resolveConfig(output)) ?? {};
const source = await format(
  `/** GENERATED by npm run codegen — do not edit manually. */
export const OPENAPI_CONTRACT_SHA256 = ${JSON.stringify(contractHash)} as const;
export const GENERATED_ROUTES = ${JSON.stringify(routes, null, 2)} as const;
export type GeneratedOperationId = keyof typeof GENERATED_ROUTES;

export function generatedPath(
  operationId: GeneratedOperationId,
  params: Record<string, string | number> = {},
): string {
  const template = GENERATED_ROUTES[operationId].template as string;
  return template.replace(/\\{([^}]+)\\}/g, (_match, name: string) => {
    const value = params[name];
    if (value === undefined) throw new Error(\`Missing path parameter \${name} for \${operationId}\`);
    return encodeURIComponent(String(value));
  });
}
`,
  { ...prettierConfig, parser: "typescript" },
);

if (process.argv.includes("--check")) {
  const existing = await fs.readFile(output, "utf8").catch(() => "");
  if (existing !== source) {
    process.stderr.write("Generated SDK routes are stale. Run npm run codegen.\n");
    process.exitCode = 1;
  }
} else {
  await fs.writeFile(output, source, "utf8");
}
