import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import {
  ROUTES,
  generateOpenApi,
  operationIdFor,
  validateOpenApiDocument,
} from "../../core/src/daemon/api.js";

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const output = path.resolve(currentDir, "../src/generated.ts");
const document = generateOpenApi();
const errors = validateOpenApiDocument(document);
if (errors.length) throw new Error(`OpenAPI conformance failed:\n${errors.join("\n")}`);
const contractHash = createHash("sha256").update(JSON.stringify(document)).digest("hex");
const routes = Object.fromEntries(
  ROUTES.map((route) => [
    operationIdFor(route),
    { method: route.method.toUpperCase(), template: route.path },
  ]),
);
const paths = document.paths as Record<string, Record<string, Record<string, unknown>>>;
const operations = Object.fromEntries(
  ROUTES.map((route) => {
    const operation = paths[route.path]![route.method]!;
    const requestSchema = (
      operation.requestBody as
        | { content?: { "application/json"?: { schema?: Record<string, unknown> } } }
        | undefined
    )?.content?.["application/json"]?.schema;
    const responses = operation.responses as Record<
      string,
      { content?: Record<string, { schema?: Record<string, unknown> }> }
    >;
    const successStatus = route.response === 204 ? "204" : "200";
    const successContent = responses[successStatus]?.content ?? {};
    const responseMediaType = Object.keys(successContent)[0] ?? null;
    return [
      operationIdFor(route),
      {
        method: route.method.toUpperCase(),
        template: route.path,
        tag: route.tag,
        requestSchema: requestSchema ?? null,
        responseStatus: Number(successStatus),
        responseMediaType,
        responseSchema: responseMediaType ? successContent[responseMediaType]?.schema ?? null : null,
        parameters: operation.parameters ?? [],
      },
    ];
  }),
);
const prettierConfig = (await resolveConfig(output)) ?? {};
const source = await format(
  `/** GENERATED by npm run codegen — do not edit manually. */
export const OPENAPI_CONTRACT_SHA256 = ${JSON.stringify(contractHash)} as const;
export const GENERATED_OPERATIONS = ${JSON.stringify(operations, null, 2)} as const;
export const GENERATED_ROUTES = ${JSON.stringify(routes, null, 2)} as const;
export type GeneratedOperationId = keyof typeof GENERATED_OPERATIONS;

export function generatedPath(
  operationId: GeneratedOperationId,
  params: Record<string, string | number> = {},
): string {
  const template = GENERATED_ROUTES[operationId].template as string;
  return template.replace(/\\{([^}]+)\\}/g, (_match, name: string) => {
    const value = params[name];
    if (value === undefined) throw new Error(\`Missing path parameter \${name} for \${operationId}\`);
    return encodeURIComponent(String(value));
  });
}

type GeneratedJsonSchema = {
  type?: string;
  required?: readonly string[];
  properties?: Record<string, GeneratedJsonSchema>;
  items?: GeneratedJsonSchema;
  additionalProperties?: boolean;
  enum?: readonly unknown[];
  const?: unknown;
  oneOf?: readonly GeneratedJsonSchema[];
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
  minimum?: number;
  maximum?: number;
  pattern?: string;
};

function sameGeneratedValue(left: unknown, right: unknown): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

function generatedSchemaIssues(value: unknown, schema: GeneratedJsonSchema, at = "$"): string[] {
  const issues: string[] = [];
  if (schema.const !== undefined && !sameGeneratedValue(value, schema.const)) issues.push(at + ": const");
  if (schema.enum && !schema.enum.some((item) => sameGeneratedValue(item, value))) issues.push(at + ": enum");
  if (schema.oneOf) {
    const matches = schema.oneOf.filter((branch) => generatedSchemaIssues(value, branch, at).length === 0).length;
    if (matches !== 1) issues.push(at + ": oneOf");
  }
  const object = value !== null && typeof value === "object" && !Array.isArray(value);
  const validType = schema.type === undefined ||
    (schema.type === "object" && object) ||
    (schema.type === "array" && Array.isArray(value)) ||
    (schema.type === "string" && typeof value === "string") ||
    (schema.type === "boolean" && typeof value === "boolean") ||
    (schema.type === "number" && typeof value === "number" && Number.isFinite(value)) ||
    (schema.type === "integer" && typeof value === "number" && Number.isSafeInteger(value));
  if (!validType) return [...issues, at + ": type"];
  if (object) {
    const record = value as Record<string, unknown>;
    for (const key of schema.required ?? []) if (!(key in record)) issues.push(at + "." + key + ": required");
    for (const [key, child] of Object.entries(schema.properties ?? {})) {
      if (key in record) issues.push(...generatedSchemaIssues(record[key], child, at + "." + key));
    }
    if (schema.additionalProperties === false) {
      for (const key of Object.keys(record)) if (!(key in (schema.properties ?? {}))) issues.push(at + "." + key + ": additionalProperties");
    }
  }
  if (Array.isArray(value)) {
    if (schema.minItems !== undefined && value.length < schema.minItems) issues.push(at + ": minItems");
    if (schema.maxItems !== undefined && value.length > schema.maxItems) issues.push(at + ": maxItems");
    if (schema.items) value.forEach((item, index) => issues.push(...generatedSchemaIssues(item, schema.items!, at + "[" + index + "]")));
  }
  if (typeof value === "string") {
    if (schema.minLength !== undefined && value.length < schema.minLength) issues.push(at + ": minLength");
    if (schema.maxLength !== undefined && value.length > schema.maxLength) issues.push(at + ": maxLength");
    if (schema.pattern && !new RegExp(schema.pattern).test(value)) issues.push(at + ": pattern");
  }
  if (typeof value === "number") {
    if (schema.minimum !== undefined && value < schema.minimum) issues.push(at + ": minimum");
    if (schema.maximum !== undefined && value > schema.maximum) issues.push(at + ": maximum");
  }
  return issues.slice(0, 64);
}

export function generatedRequestIssues(operationId: GeneratedOperationId, value: unknown): string[] {
  const schema = GENERATED_OPERATIONS[operationId].requestSchema as GeneratedJsonSchema | null;
  return schema ? generatedSchemaIssues(value, schema) : [];
}
`,
  { ...prettierConfig, parser: "typescript" },
);

if (process.argv.includes("--check")) {
  const existing = await fs.readFile(output, "utf8").catch(() => "");
  if (existing !== source) {
    process.stderr.write("Generated SDK routes are stale. Run npm run codegen.\n");
    process.exitCode = 1;
  }
} else {
  await fs.writeFile(output, source, "utf8");
}
